---
- name: Install nginx web server
  hosts: web
  become: yes

  tasks:
  - name: Install nginx web server
    apt: name=nginx state=latest

  - name: Start web server and make it enable on boot
    service: name=nginx state=started enabled=yes
